services:
  backend:
    build: .
    ports:
      - '4000:3000'
    depends_on:
      - database
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}?schema=public

  database:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=farmlink
    volumes:
      - db_data_farmlink:/var/lib/postgresql/data

volumes:
  db_data_farmlink:
